### ISSUE TITLE
netscanner crashed

### ISSUE THREAD

**Issue by janpejsa** [Chleba/netscanner#1]
[report-d98ec135-90cc-473b-946c-437a82deffcd.toml.gz](https://github.com/Chleba/netscanner/files/14006179/report-d98ec135-90cc-473b-946c-437a82deffcd.toml.gz)

os details:
Ubuntu 22.04.3 LTS
Linux 5.19.17-051917-generic #202210240939 SMP PREEMPT_DYNAMIC Mon Oct 24 09:43:01 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
cargo 1.75.0 (1d8b05cdd 2023-11-20)
cpu: 12th Gen Intel(R) Core(TM) i9-12900K

**Comment by Chleba** [comment]
`Operation not permitted` means it must be run with sudo.
Because of using `iw` in Linux and `airport` in macOS to scan wifi networks, it must be run with sudo privileges.
Also creating ICMP packets for ARP requests also needs these privileges.
`sudo netscanner` should fix that - if not, please let me know :)

**Comment by janpejsa** [comment]
thanks - instead of `sudo /home/user/.cargo/bin/netscanner` I run 
```
sudo chown root:user /home/user/.cargo/bin/netscanner
sudo chmod u+s /home/user/.cargo/bin/netscanner
```
and now I'm able to run by `netscanner` without sudo

**Comment by Chleba** [comment]
@janpejsa - that's a great option. Thanks.
