### ISSUE TITLE
[Feature request] Automatic scrolling(for lack of a better term) at Packets screen. 

### ISSUE THREAD

**Issue by rizzini** [Chleba/netscanner#16]
When analyzing a network packet monitor, it's a good idea to, unless you press up or down to navigate through the packets individually, **always** keep the cursor on the last line to keep up with what's going on at the moment it happens. Especially when talking about packets. After pressing the up or down key to navigate through the packets, gives us a way to go back to "automatic scrolling".

**Comment by Chleba** [comment]
Hi,
This feature will be in next version. I just have to figure it out how to do it easily, with just a simple state machine that would check the last row or something. I also been thinking about revert inserting new packet logs so that latest packet would be at the start of that table - but I don't know if that would be good enough for a solution.

**Comment by Chleba** [comment]
Hi,
Here (https://github.com/Chleba/netscanner/commit/2bd9d6e725389eb20c28cf729fa49515bc14bd7d) is added revert order for packet logs so newest logs are at the start so there is no need to scroll all the way down to see latest packets.
Thank You for Your patience.
