### ISSUE TITLE
Observation/BUG: order of IP is alphanumeric

### ISSUE THREAD

**Issue by AtomicRobotMan0101** [Chleba/netscanner#19]
Tiny issue. 

On my default, the IP ordering is in alphanumeric, not natural.

Perhaps change the default?

![Screenshot from 2024-03-31 18-51-52](https://github.com/Chleba/netscanner/assets/64177332/ed2d939f-505c-42cb-b94d-439eb15f0281)

**Comment by Chleba** [comment]
Hi,
Sorry for late response, here (https://github.com/Chleba/netscanner/commit/2119562975f9ab9e06041960e6c089a6365f24d4) is implemented sorting for IP addresses as requested. Thank You for you interest and bug report.
Please hold on just a little while because next version will need to address more small features and bug fixes.
